version: "3"
services:
  front:
    image: node:18
    volumes:
      - ./front:/usr/src
      - front_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn && yarn start"
    tty: true
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:4000"
      WATCHPACK_POLLING: true

  api:
    container_name: api
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - 4000:4000
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bottlist
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: bottlist
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql #データ永続化
      - ./db/sql:/docker-entrypoint-initdb.d #起動時sqlフォルダ内のsqlファイルを実行

  phpmyadmin:
    image: phpmyadmin #fpmやalpineタグは別途httpサーバが必要
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin:/sessions"
    depends_on:
      - db
volumes:
  front_modules: