// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Bottlist/bottlist/cmd/di/provider"
	"github.com/Bottlist/bottlist/pkg/adapter/handler"
	"github.com/Bottlist/bottlist/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*provider.App, error) {
	authUsecase := usecase.NewAuthUsecase()
	authHandler := handler.NewAuthHandler(authUsecase)
	app := provider.NewApp(authHandler)
	return app, nil
}
