// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Bottlist/bottlist/cmd/di/provider"
	"github.com/Bottlist/bottlist/external/mail"
	"github.com/Bottlist/bottlist/external/mysql"
	"github.com/Bottlist/bottlist/external/redis"
	"github.com/Bottlist/bottlist/middlewares"
	"github.com/Bottlist/bottlist/pkg/adapter/handler"
	"github.com/Bottlist/bottlist/pkg/domain/repository"
	"github.com/Bottlist/bottlist/pkg/domain/service"
	"github.com/Bottlist/bottlist/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*provider.App, error) {
	db := mysql.NewMySQLConnector()
	authRepository := repository.NewAuthRepository(db)
	client := redis.NewRedisConnector()
	sessionRepository := repository.NewSessionRepository(client)
	authService := service.NewAuthService(authRepository, sessionRepository)
	mailClient := mail.NewMailClient()
	authUsecase := usecase.NewAuthUsecase(authService, authRepository, mailClient)
	authHandler := handler.NewAuthHandler(authUsecase)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userUsecase := usecase.NewUserUsecase(userService, userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	sessionMiddleware := middlewares.NewSessionMiddleware(sessionRepository)
	app := provider.NewApp(authHandler, userHandler, sessionMiddleware, db)
	return app, nil
}
