// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auth_provisional_signup.proto

package _go

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostAuthProvisionalSignupRequest struct {
	Mail                 string   `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FirstNameHira        string   `protobuf:"bytes,4,opt,name=first_name_hira,json=firstNameHira,proto3" json:"first_name_hira,omitempty"`
	LastNameHira         string   `protobuf:"bytes,5,opt,name=last_name_hira,json=lastNameHira,proto3" json:"last_name_hira,omitempty"`
	ScreenName           string   `protobuf:"bytes,6,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	Birthday             string   `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirm      string   `protobuf:"bytes,9,opt,name=password_confirm,json=passwordConfirm,proto3" json:"password_confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAuthProvisionalSignupRequest) Reset()         { *m = PostAuthProvisionalSignupRequest{} }
func (m *PostAuthProvisionalSignupRequest) String() string { return proto.CompactTextString(m) }
func (*PostAuthProvisionalSignupRequest) ProtoMessage()    {}
func (*PostAuthProvisionalSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402ab83c47f5cf71, []int{0}
}
func (m *PostAuthProvisionalSignupRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PostAuthProvisionalSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PostAuthProvisionalSignupRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PostAuthProvisionalSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAuthProvisionalSignupRequest.Merge(m, src)
}
func (m *PostAuthProvisionalSignupRequest) XXX_Size() int {
	return m.Size()
}
func (m *PostAuthProvisionalSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAuthProvisionalSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostAuthProvisionalSignupRequest proto.InternalMessageInfo

func (m *PostAuthProvisionalSignupRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetFirstNameHira() string {
	if m != nil {
		return m.FirstNameHira
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetLastNameHira() string {
	if m != nil {
		return m.LastNameHira
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PostAuthProvisionalSignupRequest) GetPasswordConfirm() string {
	if m != nil {
		return m.PasswordConfirm
	}
	return ""
}

type PostAuthProvisionalSignupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAuthProvisionalSignupResponse) Reset()         { *m = PostAuthProvisionalSignupResponse{} }
func (m *PostAuthProvisionalSignupResponse) String() string { return proto.CompactTextString(m) }
func (*PostAuthProvisionalSignupResponse) ProtoMessage()    {}
func (*PostAuthProvisionalSignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_402ab83c47f5cf71, []int{1}
}
func (m *PostAuthProvisionalSignupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PostAuthProvisionalSignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PostAuthProvisionalSignupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PostAuthProvisionalSignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAuthProvisionalSignupResponse.Merge(m, src)
}
func (m *PostAuthProvisionalSignupResponse) XXX_Size() int {
	return m.Size()
}
func (m *PostAuthProvisionalSignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAuthProvisionalSignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostAuthProvisionalSignupResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PostAuthProvisionalSignupRequest)(nil), "api.PostAuthProvisionalSignupRequest")
	proto.RegisterType((*PostAuthProvisionalSignupResponse)(nil), "api.PostAuthProvisionalSignupResponse")
}

func init() { proto.RegisterFile("auth_provisional_signup.proto", fileDescriptor_402ab83c47f5cf71) }

var fileDescriptor_402ab83c47f5cf71 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd1, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0x71, 0xbb, 0xce, 0xad, 0x7d, 0xfc, 0xb3, 0x51, 0x10, 0x8b, 0x62, 0x99, 0x9b, 0xc8,
	0x2e, 0x3a, 0xd0, 0x57, 0xe0, 0xbc, 0x78, 0x92, 0x51, 0x6f, 0x5e, 0xca, 0xb3, 0x2d, 0x5b, 0x03,
	0x6d, 0x13, 0x93, 0x74, 0xe2, 0x0b, 0x11, 0x7c, 0x49, 0x1e, 0x7d, 0x09, 0x52, 0xdf, 0x85, 0x27,
	0x59, 0x4a, 0xbb, 0xe5, 0xe2, 0x2d, 0xe4, 0xfb, 0xe1, 0x47, 0x20, 0x70, 0x86, 0xb9, 0x8a, 0x23,
	0x2e, 0xd8, 0x8a, 0x4a, 0xca, 0x32, 0x4c, 0x22, 0x49, 0x97, 0x59, 0xce, 0xaf, 0xb9, 0x60, 0x8a,
	0x79, 0x36, 0x72, 0x7a, 0x72, 0xbc, 0xc2, 0x84, 0xce, 0x51, 0x91, 0x51, 0x75, 0x28, 0x6b, 0xff,
	0xdd, 0x86, 0xde, 0x84, 0x49, 0x75, 0x97, 0xab, 0x78, 0xb2, 0x99, 0x78, 0xd2, 0x0b, 0x21, 0x79,
	0xc9, 0x89, 0x54, 0xde, 0x29, 0x34, 0x53, 0xa4, 0x89, 0x6f, 0xf5, 0xac, 0xa1, 0x3b, 0x6e, 0xff,
	0x8e, 0x9b, 0xa2, 0xd1, 0xb5, 0x42, 0x7d, 0xe9, 0x5d, 0x02, 0x2c, 0xa8, 0x90, 0x2a, 0xca, 0x30,
	0x25, 0x7e, 0xc3, 0x24, 0xae, 0x4e, 0x8f, 0x98, 0x12, 0xef, 0x02, 0xdc, 0x04, 0x2b, 0x66, 0x9b,
	0xcc, 0x59, 0x17, 0xad, 0x46, 0xd0, 0xd9, 0xac, 0x45, 0x31, 0x15, 0xe8, 0x37, 0x4d, 0x7b, 0x50,
	0x4f, 0x3e, 0x50, 0x81, 0xde, 0x15, 0x1c, 0xd6, 0xb3, 0xa5, 0xdf, 0x35, 0xfd, 0x7e, 0xb5, 0xad,
	0xf9, 0x10, 0xf6, 0xe4, 0x4c, 0x10, 0x92, 0x95, 0xef, 0x68, 0x99, 0x16, 0xca, 0xa6, 0x5f, 0x32,
	0x00, 0x67, 0x4a, 0x85, 0x8a, 0xe7, 0xf8, 0xe6, 0xb7, 0xb7, 0x19, 0x84, 0x75, 0x58, 0x23, 0x8e,
	0x52, 0xbe, 0x32, 0x31, 0xf7, 0x9d, 0x6d, 0xe4, 0x84, 0x75, 0xf0, 0x6e, 0xa0, 0x5b, 0x9d, 0xa3,
	0x19, 0xcb, 0x16, 0x54, 0xa4, 0xbe, 0x6b, 0xe2, 0x4e, 0x05, 0xee, 0xcb, 0xde, 0x1f, 0xc0, 0xf9,
	0x3f, 0xdf, 0x22, 0x39, 0xcb, 0x24, 0x19, 0x1f, 0x7d, 0x16, 0x81, 0xf5, 0x55, 0x04, 0xd6, 0x77,
	0x11, 0x58, 0x1f, 0x3f, 0xc1, 0xce, 0xb3, 0x3d, 0x5a, 0xb2, 0x69, 0x4b, 0x7f, 0xed, 0xed, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x1c, 0x6d, 0x41, 0x19, 0x02, 0x00, 0x00,
}

func (m *PostAuthProvisionalSignupRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PostAuthProvisionalSignupRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PostAuthProvisionalSignupRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PasswordConfirm) > 0 {
		i -= len(m.PasswordConfirm)
		copy(dAtA[i:], m.PasswordConfirm)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.PasswordConfirm)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Birthday) > 0 {
		i -= len(m.Birthday)
		copy(dAtA[i:], m.Birthday)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.Birthday)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ScreenName) > 0 {
		i -= len(m.ScreenName)
		copy(dAtA[i:], m.ScreenName)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.ScreenName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LastNameHira) > 0 {
		i -= len(m.LastNameHira)
		copy(dAtA[i:], m.LastNameHira)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.LastNameHira)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FirstNameHira) > 0 {
		i -= len(m.FirstNameHira)
		copy(dAtA[i:], m.FirstNameHira)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.FirstNameHira)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LastName) > 0 {
		i -= len(m.LastName)
		copy(dAtA[i:], m.LastName)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.LastName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FirstName) > 0 {
		i -= len(m.FirstName)
		copy(dAtA[i:], m.FirstName)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.FirstName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Mail) > 0 {
		i -= len(m.Mail)
		copy(dAtA[i:], m.Mail)
		i = encodeVarintAuthProvisionalSignup(dAtA, i, uint64(len(m.Mail)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PostAuthProvisionalSignupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PostAuthProvisionalSignupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PostAuthProvisionalSignupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthProvisionalSignup(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthProvisionalSignup(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PostAuthProvisionalSignupRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mail)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.FirstName)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.LastName)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.FirstNameHira)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.LastNameHira)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.ScreenName)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.Birthday)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	l = len(m.PasswordConfirm)
	if l > 0 {
		n += 1 + l + sovAuthProvisionalSignup(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PostAuthProvisionalSignupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAuthProvisionalSignup(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthProvisionalSignup(x uint64) (n int) {
	return sovAuthProvisionalSignup(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PostAuthProvisionalSignupRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthProvisionalSignup
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PostAuthProvisionalSignupRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PostAuthProvisionalSignupRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstNameHira", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstNameHira = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastNameHira", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastNameHira = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScreenName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScreenName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Birthday", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Birthday = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PasswordConfirm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PasswordConfirm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthProvisionalSignup(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PostAuthProvisionalSignupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthProvisionalSignup
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PostAuthProvisionalSignupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PostAuthProvisionalSignupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipAuthProvisionalSignup(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthProvisionalSignup
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthProvisionalSignup(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthProvisionalSignup
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthProvisionalSignup
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthProvisionalSignup
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthProvisionalSignup
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthProvisionalSignup
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthProvisionalSignup        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthProvisionalSignup          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthProvisionalSignup = fmt.Errorf("proto: unexpected end of group")
)
